export const GET_APPLICATION_LIST = "GET_APPLICATION_LIST";
export const GET_APPLICATION_DETAILS = "GET_APPLICATION_DETAILS";
export const APPLICATION_PAGINATION = "APPLICATION_PAGINATION"
export const SET_APPLICATION_FALSE = "SET_APPLICATION_FALSE"
export const SET_APPLICATION_STATUS_FALSE = "SET_APPLICATION_STATUS_FALSE"
export const SET_APPLICATION_INPUT_FALSE = "SET_APPLICATION_INPUT_FALSE"
export const IS_LOAD_APPLICATION = "IS_LOAD_APPLICATION";
export const GET_APPLICATION_INPUT = "GET_APPLICATION_INPUT";
export const AFTER_SUCCESS_APPLICATION = "AFTER_SUCCESS_APPLICATION"
export const SET_APPLICATION_UPDATED = "SET_APPLICATION_UPDATED";
export const SET_BUSINESS_UPDATED = "SET_BUSINESS_UPDATED";
export const IS_LOAD_APP = "IS_LOAD_APP";
export const IS_LOAD_BUSINESS = "IS_LOAD_BUSINESS";
export const IS_LOAD_SIGN = "IS_LOAD_SIGN";
// ---------------------qualify---------------------------
export const AFTER_SUCCESS_APPLICATION_QUALIFY = "AFTER_SUCCESS_APPLICATION_QUALIFY"
export const SET_FALSE_APPLICATION_QUALIFY = "SET_FALSE_APPLICATION_QUALIFY"
export const GET_QUALIFY_APPLICATION = "GET_QUALIFY_APPLICATION";

// =======vat==============
export const GET_VAT_LIST = "GET_VAT_LIST";
// ================doc-------------------


export const DELETE_DOC = "DELETE_DOC";
export const SET_NEW_DOC_INPUT = "SET_NEW_DOC_INPUT";
export const ADD_NEW_DOC = "ADD_NEW_DOC";
export const ADD_NEW_BANK = "ADD_NEW_BANK";
export const SUCCESS_DOC = "SUCCESS_DOC";
export const SET_DOC_UPDATED = "SET_DOC_UPDATED";

// sign
export const SEND_SIGNING_REQUEST = "SEND_SIGNING_REQUEST";
export const AFTER_SUCCESS_SIGNING = "AFTER_SUCCESS_SIGNING";
export const AFTER_FAILED_SIGNING = "AFTER_FAILED_SIGNING";
export const SET_SIGINING_FALSE = "SET_SIGINING_FALSE";

export const GET_QUOTE_OWNER = "GET_QUOTE_OWNER";
export const SET_QUOTE_OWNER = "SET_QUOTE_OWNER";
export const REMOVE_APPLICATION_OWNER = "REMOVE_APPLICATION_OWNER";
export const IS_APPLICATION_OWNER_DELETED = "IS_APPLICATION_OWNER_DELETED";


export const SUBMIT_APPLICATION_TO_BANK = "SUBMIT_APPLICATION_TO_BANK";
export const AFTER_SUBMIT_BANK = "AFTER_SUBMIT_BANK";
export const SET_SUBMIT_FALSE = "SET_SUBMIT_FALSE";


export const SET_BANK_FALSE = "SET_BANK_FALSE";
export const AFTER_SUCCESS_BANK = "AFTER_SUCCESS_BANK";
export const GET_BANK_INPUT = "GET_BANK_INPUT";
export const GET_BANK_DETAILS = "GET_BANK_DETAILS";
export const GET_DEBIT_BANK_DETAILS = "GET_DEBIT_BANK_DETAILS";

export const GET_SITE_VISIT_DOWNLOAD_BANK = "GET_SITE_VISIT_DOWNLOAD_BANK";