export const GET_LEADS_LIST = "GET_LEADS_LIST";
export const GET_INDUSTRY_LIST = "GET_INDUSTRY_LIST";
export const IS_LOAD_LEADS = "IS_LOAD_LEADS";
export const GET_LEADS_INPUT = "GET_LEADS_INPUT";
export const GET_LEGAL_INPUT = "GET_LEGAL_INPUT";
export const AFTER_SUCCESS_LEADS = "AFTER_SUCCESS_LEADS"
export const SET_FALSE = "SET_FALSE"
export const AFTER_SUCCESS_UPDATE = "AFTER_SUCCESS_UPDATE"
export const SET_FALSE_UPDATE_LEADS= "SET_FALSE_UPDATE_LEADS"
export const LEAD_QUALIFY_CHECK_FALSE= "LEAD_QUALIFY_CHECK_FALSE"
export const LEADS_PAGINATION = "LEADS_PAGINATION"
export const GET_LEADS_DETAILS = "GET_LEADS_DETAILS"
export const LEADS_DETAILS_PAGINATION = "LEADS_DETAILS_PAGINATION"
export const SET_LEADS_UPDATED = "SET_LEADS_UPDATED"

export const GET_USER_LIST = "GET_USER_LIST";
export const GET_COUNTRY_LIST = "GET_COUNTRY_LIST";
export const SET_FUNCTION_CALLED = "SET_FUNCTION_CALLED";
export const SET_TYPE_FALSE = "SET_TYPE_FALSE";


export const GET_CARD_TERMINAL_PRODUCT = "GET_CARD_TERMINAL_PRODUCT";
export const SET_CARD_TERMINAL_PRODUCT = "SET_CARD_TERMINAL_PRODUCT";
export const REMOVE_CARD_TERMINAL_PRODUCT = "REMOVE_CARD_TERMINAL_PRODUCT";
export const IS_CARD_TERMINAL_PRODUCT_DELETED = "IS_CARD_TERMINAL_PRODUCT_DELETED";

export const GET_ECOMMERCE_PRODUCT = "GET_ECOMMERCE_PRODUCT";
export const SET_ECOMMERCE_PRODUCT = "SET_ECOMMERCE_PRODUCT";
export const REMOVE_ECOMMERCE_PRODUCT = "REMOVE_ECOMMERCE_PRODUCT";
export const IS_ECOMMERCE_PRODUCT_DELETED = "IS_ECOMMERCE_PRODUCT_DELETED";

export const GET_EPOS_PRODUCT = "GET_EPOS_PRODUCT";
export const SET_EPOS_PRODUCT = "SET_EPOS_PRODUCT";
export const REMOVE_EPOS_PRODUCT = "REMOVE_EPOS_PRODUCT";
export const IS_EPOS_PRODUCT_DELETED = "IS_EPOS_PRODUCT_DELETED";
// ==========

export const GET_COMPANY_HOUSE_LIST = "GET_COMPANY_HOUSE_LIST";
export const GET_COMPANY_HOUSE_DETAILS = "GET_COMPANY_HOUSE_DETAILS";
export const GET_COMPANY_OFFICERS_DETAILS = "GET_COMPANY_OFFICERS_DETAILS";



export const GET_POST_CODE_LIST = "GET_POST_CODE_LIST";
export const GET_POST_CODE_ADDRESS = "GET_POST_CODE_ADDRESS";
export const SET_POST_CODE = "SET_POST_CODE";
export const REMOVE_POST_CODE = "REMOVE_POST_CODE";
export const IS_POST_CODE_DELETED = "IS_POST_CODE_DELETED";
export const SUCCESS_POST_CODE = "SUCCESS_POST_CODE";


export const GET_QUALIFY_LIST = "GET_QUALIFY_LIST"
export const AFTER_SUCCESS_QUALIFY = "AFTER_SUCCESS_QUALIFY"
export const QUALIFY_STATUS = "QUALIFY_STATUS"
export const SET_FALSE_LEAD_QUALIFY = "SET_FALSE_LEAD_QUALIFY"
export const SET_FALSE_QUALIFY = "SET_FALSE_QUALIFY"
export const GET_QUALIFY_LEAD = "GET_QUALIFY_LEAD";