export const GET_PRICE_QUOTE_LIST = "GET_PRICE_QUOTE_LIST";
export const GET_PRICE_QUOTE_DETAILS = "GET_PRICE_QUOTE_DETAILS";
export const IS_LOAD_QUOTE = "IS_LOAD_QUOTE";
export const PRICE_QUOTE_PAGINATION = "PRICE_QUOTE_PAGINATION"
export const SET_PRICE_QUOTE_FALSE = "SET_PRICE_QUOTE_FALSE"
export const IS_LOAD_PRICE_QUOTE = "IS_LOAD_PRICE_QUOTE";
export const AFTER_SUCCESS_QUOTE_QUALIFY = "AFTER_SUCCESS_QUOTE_QUALIFY";
export const QUOTE_QUALIFY_CHECK = "QUOTE_QUALIFY_CHECK";
export const SET_FALSE_QUOTE_QUALIFY = "SET_FALSE_QUOTE_QUALIFY";
export const GET_PRICE_QUOTE_INPUT = "GET_PRICE_QUOTE_INPUT";
export const AFTER_SUCCESS_PRICE_QUOTE = "AFTER_SUCCESS_PRICE_QUOTE"
export const SET_PRICEQUOTE_UPDATED = "SET_PRICEQUOTE_UPDATED";
export const GET_QUALIFY_APPLICATION = "GET_QUALIFY_APPLICATION";
export const AFTER_SUCCESS_APPLICATION_QUALIFY = "AFTER_SUCCESS_APPLICATION_QUALIFY"
export const SET_FALSE_APPLICATION_QUALIFY = "SET_FALSE_APPLICATION_QUALIFY"

export const REMOVE_QUOTE_OWNER = "REMOVE_QUOTE_OWNER"
export const SET_PRICE_QUOTE_OWNER_INPUT = "SET_PRICE_QUOTE_OWNER_INPUT"
export const GET_PRICE_QUOTE_OWNER = "GET_PRICE_QUOTE_OWNER"

export const GET_PRICE_QUOTE_OWNER_CONTACT = "GET_PRICE_QUOTE_OWNER_CONTACT"
export const SET_QUOTE_OWNER_CONTACT_INPUT = "SET_QUOTE_OWNER_CONTACT_INPUT"
export const UPDATE_QUOTE_OWNER_CONTACT = "UPDATE_QUOTE_OWNER_CONTACT"


export const GET_QUOTE_CARD_TERMINAL_PRODUCT = "GET_QUOTE_CARD_TERMINAL_PRODUCT";
export const SET_QUOTE_CARD_TERMINAL_PRODUCT = "SET_QUOTE_CARD_TERMINAL_PRODUCT";
export const REMOVE_QUOTE_CARD_TERMINAL_PRODUCT = "REMOVE_QUOTE_CARD_TERMINAL_PRODUCT";
export const IS_QUOTE_CARD_TERMINAL_PRODUCT_DELETED = "IS_QUOTE_CARD_TERMINAL_PRODUCT_DELETED";

export const GET_QUOTE_ECOMMERCE_PRODUCT = "GET_QUOTE_ECOMMERCE_PRODUCT";
export const SET_QUOTE_ECOMMERCE_PRODUCT = "SET_QUOTE_ECOMMERCE_PRODUCT";
export const REMOVE_QUOTE_ECOMMERCE_PRODUCT = "REMOVE_QUOTE_ECOMMERCE_PRODUCT";
export const IS_QUOTE_ECOMMERCE_PRODUCT_DELETED = "IS_QUOTE_ECOMMERCE_PRODUCT_DELETED";

export const GET_QUOTE_EPOS_PRODUCT = "GET_QUOTE_EPOS_PRODUCT";
export const SET_QUOTE_EPOS_PRODUCT = "SET_QUOTE_EPOS_PRODUCT";
export const REMOVE_QUOTE_EPOS_PRODUCT = "REMOVE_QUOTE_EPOS_PRODUCT";
export const IS_QUOTE_EPOS_PRODUCT_DELETED = "IS_QUOTE_EPOS_PRODUCT_DELETED";