export const GET_ALL_PRODUCT_LIST = "GET_ALL_PRODUCT_LIST";
export const IS_LOAD_COMMON = "IS_LOAD_COMMON";

export const GET_IMAGE_INPUT = "GET_IMAGE_INPUT";
export const IS_SUCCESS_IMAGE = "IS_SUCCESS_IMAGE";
export const EMAIL_VERIFICATION_DETAILS = "EMAIL_VERIFICATION_DETAILS";
export const CONTACT_EMAIL_VERIFICATION_DETAILS = "CONTACT_EMAIL_VERIFICATION_DETAILS";
export const GET_NOTIFICATION_LIST = "GET_NOTIFICATION_LIST";
export const GET_PROFILE_DETAILS = "GET_PROFILE_DETAILS";